version: "3.9"

services:
# edumeet
  edumeet:
    env_file: .env
    image: ${REPOSITORY}/${EDUMEET}:${TAG}
    build:
      args:
        - BASEDIR=${BASEDIR}
        - EDUMEET=${EDUMEET}
        - NODE_ENV=${NODE_ENV}
        - SERVER_DEBUG=${SERVER_DEBUG}
        - GIT_SERVER=${GIT_SERVER}
        - REPOSITORY=${REPOSITORY}
        - BRANCH=${BRANCH}
      context: ./
    restart: unless-stopped
    volumes:
      - ./configs/server/config.js:${BASEDIR}/${EDUMEET}/server/dist/config.js:ro
      - ./configs/server/config.yaml:${BASEDIR}/${EDUMEET}/server/dist/config.yaml:ro
      - ./certs:${BASEDIR}/${EDUMEET}/server/dist/certs
      - ./configs/app/config.js:${BASEDIR}/${EDUMEET}/server/dist/public/config.js:ro
      - ./images:${BASEDIR}/${EDUMEET}/server/dist/public/images
      - ./privacy:${BASEDIR}/${EDUMEET}/server/dist/public/static/privacy
    network_mode: "host"
    stdin_open: true
    tty: true
#   environment:
#     - DEBUG=mediasoup*
