version: "3.9"

services:
# edumeet
  edumeet:
    env_file: .env
    image: ${REPOSITORY}/${EDUMEET}:${TAG}
    depends_on: 
      - redis
    restart: unless-stopped
    volumes:
      - ./configs/server/config.js:${BASEDIR}/${EDUMEET}/server/dist/config.js:ro
      - ./configs/server/config.yaml:${BASEDIR}/${EDUMEET}/server/dist/config.yaml:ro
      - ./configs/app/config.js:${BASEDIR}/${EDUMEET}/server/dist/public/config.js:ro
      - ./certs:${BASEDIR}/${EDUMEET}/server/dist/certs
      - ./images:${BASEDIR}/${EDUMEET}/server/dist/public/images
      - ./privacy:${BASEDIR}/${EDUMEET}/server/dist/public/static/privacy
    network_mode: "host"
    stdin_open: true
    tty: true
#   environment:
#     - DEBUG=edumeet*

  redis:
    image: redis:latest
    network_mode: "host"
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    volumes:
      - ./configs/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro